#!/bin/bash

if [ $# -ne 1 ]
    then
        echo "Run with 'activate' argument!"
        exit
    fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

cat > src/lib/NemesisCore/NemesisCoreMainHeaderConfig.hpp << EOF
#define NEMESIS_VERSION        "18.${GITREVS}.${GITHASH}"
#define NEMESIS_BUILDTIME      "${DATE}"
EOF

echo ""
echo "Nemesis Revision: 18.$GITREVS.$GITHASH ($DATE)"

